"""updated the transaction model to add balance_after

Revision ID: 63d268cd8b9c
Revises: fe783ee6d8f5
Create Date: 2024-08-09 01:27:52.151514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d268cd8b9c'
down_revision = 'fe783ee6d8f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_after', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('balance_after')

    # ### end Alembic commands ###
