"""Add phone and password to the database

Revision ID: c9a8cbe5e37b
Revises: edc3538760c9
Create Date: 2024-08-04 15:05:28.914692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9a8cbe5e37b'
down_revision = 'edc3538760c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=180), nullable=False))
        batch_op.alter_column('balance',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('password_hash')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
